### ISSUE TITLE
Возникает ошибка, скорее всего после перехода в chroot

### ISSUE THREAD

**Issue by telegramcores** [readysloth/Workspace-recreation#4]
Traceback (most recent call last):
  File "/root/WR/partitioning.py", line 114, in <module>
  File "/root/WR/preinstallation.py", line 31, in preinstall
  File "/root/WR/utils.py", line 33, in call_cmd_and_print_cmd
  File "/root/WR/utils.py", line 18, in call_cmd
FileNotFoundError: [Errno 2] No such file or directory: '/dev/tty3'

**Comment by telegramcores** [comment]
Оказалось, что путь к stage3 не определяется и поэтому не скачивается.

**Comment by readysloth** [comment]
Проблема решилась?
Вообще ошибка выглядит так, будто нет третьего терминала. Можно переключиться на другой терминал через ctrl+alt+Fномер-терминала. Т.е для третьего это будет ctrl+alt+F3.

Можно самостоятельно запатчить этот момент, так как запись в tty2/tty3 нужна только для логгирования stderr и stdout запускаемых процессов.

**Comment by telegramcores** [comment]
В stage3.sh заменил строки на
...
 FOLDER_COOSER="current-stage3-${PROCESSOR}-openrc/"
...
grep "stage3-${PROCESSOR}-openrc-[0-9]\{8\}T[0-9]\{6\}" |
После этого скачивается.

Все работает до строки в compiling.py
  call_cmd_and_print_cmd('''echo '>sys-devel/gcc-10.3.0-r2' >> /etc/portage/package.mask''')
Если не разберусь создам новую тему.

**Comment by telegramcores** [comment]
call_cmd_and_print_cmd('''echo '>sys-devel/gcc-10.3.0-r2' >> /etc/portage/package.mask''')
Возникает ошибка при обращении к  /usr/lib/python3.9/subprocess.py, видно что-то поменялось в параметрах вызова функции.

**Comment by readysloth** [comment]
Указанные ошибки поправил, спасибо :)
В генту поменялись некоторые места, о которых в коде были иные предположения
